### ISSUE TITLE
你好，最近也在关注 GCN 方面的工作，希望可以一起学习交流

### ISSUE THREAD

**Issue by wangxiao5791509** [Eilene/spatio-temporal-paper-list#1]
你好，最近也在关注 GCN 方面的工作，希望可以一起学习交流，QQ：1179429753

**Comment by Eilene** [comment]
你好，添加好友有问题验证，回答你的真实姓名～我的微信qq都是1097810358～

**Comment by wangxiao5791509** [comment]
Here is a wechat group for GCN technique...
![qq 20181218210237](https://user-images.githubusercontent.com/12805786/50155919-4e500700-0308-11e9-9bbd-83450b8eb274.png)
